<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            
            <a class="brand" href="#">Online Payment</a>
            <div class="nav-collapse collapse">
                <p class="navbar-text pull-right">
                Logged in as <a href="#" class="navbar-link">buyer</a>|<a href=/manage/hotel/info>Admin</a>
                </p>
                <ul class="nav">
                    <li><a href="#">账户设置</a></li>
                    <li><a href="order_manage.html">我是买家</a></li>
                    <li><a href="#contact">我是卖家</a></li>
                    <li><a href="#contact">淘宝贝</a></li>
                    <li class="active"><a href="/">在线预订</a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>
</div>
