<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            
            <a class="brand" href="#">Online Payment</a>
            <div class="nav-collapse collapse">
                <p class="navbar-text pull-right">
                Logged in as <a href="#" class="navbar-link">buyer</a>|<a href=/manage/hotel/info>Admin</a>
                </p>
                <ul class="nav">
                    <li><a href="#">账户设置</a></li>
                    <li><a href="order_manage.html">我是买家</a></li>
                    <li><a href="#contact">我是卖家</a></li>
                    <li><a href="#contact">淘宝贝</a></li>
                    <li class="active"><a href="/">在线预订</a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>
</div>
      <div id="myCarousel" class="carousel slide">
          <div class="carousel-inner">
              <div class="item active" >
                  <img src="../img/logo1.jpg" alt="" width="100%">
                      <div class="container">
                          <div class="carousel-caption">
                              <h1 style="color:#888888">方便快捷</h1>
                              <p class="lead">您可以轻松的完成整个交易流程。</p>
                          </div>
                      </div>
                      </div>
              <div class="item">
                  <img src="../img/logo3.jpg" alt="" width="100%">
                      <div class="container">
                          <div class="carousel-caption">
                              <h1 style="color:#888888">在线支付</h1>
                              <p class="lead">您可以在家里或者办公的场所完成各种交易行为。</p>
                          </div>
                      </div>
                      </div>
              <div class="item">
                  <img src="../img/logo2.jpg" alt="" width="100%">
                      <div class="container">
                          <div class="carousel-caption">
                              <h1 style="color:#888888">退款管理</h1>
                              <p class="lead">清楚的退款流程给您安全的交易保障。</p>
                          </div>
                      </div>
                      </div>
          </div>
          <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
          <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
      </div><!-- /.carousel -->
