<li class="nav-header">酒店</li>
<li id="nlHotel"><a href="/manage/hotel/info">酒店信息管理</a></li>
<li id="nlHotelRoom"><a href="/manage/hotel/room">酒店房间信息管理</a></li>
<li id="nlHotelTransaction"><a href="/manage/hotel/transaction">酒店订单管理</a></li>
<li id="nlHotelComment"><a href="/manage/hotel/comment">酒店评价管理</a></li>
<li class="nav-header">航班</li>
<li id="nlFlight"><a href="/manage/flight/info">航班信息管理</a></li>
<li id="nlFlightTransaction"><a href="/manage/flight/transaction">航班订单管理</a></li>
<li id="nlFlightComment"><a href="/manage/flight/comment">航班评价管理</a></li>
<script> $('#{{active}}').addClass('active'); </script>